// Generated by Wrangler by running `wrangler types ./src/types/wrangler/worker-configuration.d.ts --env-interface=Environment --x-include-runtime=./src/types/wrangler/runtime.d.ts --experimental-json-config`

interface Environment {
	TELEGRAM_BOT_TOKEN: string;
	ALLOWED_USERS: string;
	SEARCH_SERVER_ADDRESS: string;
	SEARCH_SERVER_PASSWORD: string;
}
