name: Build Server

on:
  workflow_call:
    outputs:
      artifact_name:
        description: The name of the created artifact
        value: ${{ jobs.build.outputs.artifact_name }}
jobs:
  build:
    name: Build server
    environment: ${{ github.ref_name == 'master' && 'production' || 'development' }}
    runs-on: ubuntu-24.04-arm
    env:
      artifact_name: image-search-server-${{ vars.SERVER_ARCHITECTURE }}-${{ github.sha }}
    outputs:
      artifact_name: ${{ env.artifact_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
        with:
          platforms: ${{ vars.SERVER_ARCHITECTURE }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
        with:
          platforms: linux/${{ vars.SERVER_ARCHITECTURE }}

      - name: Build image
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: image-search-server:latest
          platforms: linux/${{ vars.SERVER_ARCHITECTURE }}
          outputs: type=docker,dest=./image-search-server.tar

      - name: Upload image
        id: upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: ${{ env.artifact_name }}
          path: |
            ./image-search-server.tar
            ./docker-compose.yml
