name: Build Server

on:
  workflow_call:
    outputs:
      artifact_name:
        description: The name of the created artifact
        value: ${{ jobs.build.outputs.artifact_name }}
jobs:
  build:
    name: Build server
    environment: ${{ github.ref_name == 'master' && 'production' || 'development' }}
    runs-on: ubuntu-24.04-arm
    env:
      artifact_name: image-search-server-${{ vars.SERVER_ARCHITECTURE }}-${{ github.sha }}
    outputs:
      artifact_name: ${{ env.artifact_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Build image
        run: |
          mkdir -p output
          cp docker-compose.yml output/
          docker build --platform linux/${{ vars.SERVER_ARCHITECTURE }} --pull --rm -f 'Dockerfile' -t image-search-server:latest '.'
          docker save -o output/image-search-server.tar image-search-server:latest

      - name: Upload image
        id: upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: ${{ env.artifact_name }}
          path: output/
