name: Deploy Bot

on:
  push:
    branches:
      - master
      - dev
    paths:
      - packages/bot/src/**
      - packages/bot/package.json
      - packages/bot/wrangler.json
      - .github/workflows/deploy_bot.yml

jobs:
  check-token:
    name: Check for Cloudflare API token
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'production' || 'development' }}
    outputs:
      is_set: ${{ steps.check.outputs.is_set }}
    steps:
      - name: Perform check
        id: check
        run: |
          if [[ '${{ secrets.CLOUDFLARE_API_TOKEN }}' ]]; then
            echo "is_set=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_set=false" >> "$GITHUB_OUTPUT"
            echo "Cloudflare API token is not set. Skipping deployment."
          fi

  check-package:
    name: Check package
    needs: check-token
    if: ${{ needs.check-token.outputs.is_set == 'true' }}
    uses: ./.github/workflows/check.yml
    secrets: inherit
    with:
      cwd: packages/bot

  deploy:
    name: Deploy bot
    runs-on: ubuntu-24.04-arm
    needs: check-package
    environment: ${{ github.ref_name == 'master' && 'production' || 'development' }}
    defaults:
      run:
        working-directory: packages/bot
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: lts/*

      - name: Install dependencies
        run: bun install --frozen-lockfile --production

      - name: Build & Deploy
        run: bun run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
